### PR TITLE
check for audio stream existence, early return

### PR DESCRIPTION
**Pull request by tgabi333**
With chrome 45 beta, i got a situation where audio and video was requested but got only video feed.

### CODE REVIEW

**Comment by xdumaine** [comment]
It's possible that I'm missing something, but I look at this about five times. Did you not actually add a check for audio stream existence? All I see is nesting change/if block inversion.

**Comment by tgabi333** [comment]
stream.getAudioTracks().length do the check, otherwise you get a javascript error when try to instatiate hark and gaincontrol.

**Comment by xdumaine** [comment]
I think you should maybe file this as an issue with chrome. If audio and video were requested but no audio tracks were available that should be a constraintsNotSatisfied error. Is it reliably reproducible?

**Comment by xdumaine** [comment]
Otherwise, this change makes an assumption that silently failing to fulfill constraints is acceptable, which, for application developers, is almost certainly not.

**Comment by tgabi333** [comment]
I had a situation with chrome beta, that i denied to give access to my cam and mic, and i got webcam without audio, and the code failed. I cannot reproduce now, however that time, i managed to test it out.

I think it's a harmless sanity check.

**Pull request closed without merging**
