### PR TITLE
Add ability to fallback to audio if the user doesn't have a camera

### PR DESCRIPTION
**Pull request by zusatzstoff**
I would like to propose a further optional flag called ``audioFallback``. It gives users the ability to participate on mixed audio and video sessions.

### CODE REVIEW

**Comment by zusatzstoff** [comment]
@fippo, @legastero some feedback to this PR would be awesome :+1

**Comment by fippo** [comment]
i tend to let the app handle those things but... LGTM. @xdumaine let's merge this as well before bumping the version?

**Comment by xdumaine** [comment]
I agree. Looks good.

**Comment by xdumaine** [comment]
One thing I did just notice, this audio fallback would fail if you're passing any optional constraints to video (i.e., anything other than `true`), which my app does all the time. You might consider another PR to allow that scenario @zusatzstoff

**Comment by fippo** [comment]
@xdumaine good catch. shall we fix that before publishing? Seems easy by checking for not false.

**Comment by xdumaine** [comment]
@fippo Yeah, probably better to just do it now.

**Comment by fippo** [comment]
let me do it. and then figure out where my npm creds are

**Comment by fippo** [comment]
done in 1.1.1. Heck, i miss travis tests, should add that.

**Comment by zusatzstoff** [comment]
Thanks a lot for merging this. Will help us to improve our video client.

**Pull request merged**
