### PR TITLE
add MediaStreamTrack.getSources wrapper

### PR DESCRIPTION
**Pull request by fippo**
while getSources is still a little too unstable, I think we should wrap it in localMedia instead of accessing it directly. @legastero?

### CODE REVIEW

**Comment by fippo** [comment]
wait, didn't we add that or was that somewhere else @legastero?

**Comment by xdumaine** [comment]
For another reference, [here's how](https://github.com/xdumaine/enumerateDevices/blob/master/index.js) I implemented it, for firefox and chrome to normalize behaviors as close to the spec as possible.

**Comment by fippo** [comment]
still looking to use adapter.js instead... but can't get those guys to decide on a proper module name :-)

**Comment by fippo** [comment]
ah, we're now using adapter.

**Pull request closed without merging**
