### PR TITLE
change DevicesNotFoundError -> NotFoundError

### PR DESCRIPTION
**Pull request by fippo**
fixes https://github.com/andyet/SimpleWebRTC/issues/628

### CODE REVIEW

**Comment by fippo** [comment]
hrm... I tried to publish 4.0.1 but it seems you did and forgot to push?

**Comment by fippo** [comment]
@xdumaine ^^

**Comment by xdumaine** [comment]
I'll try to get it pushed up. Not sure which computer that's on. You should
be safe to push 4.0.2 in the meantime. does that work for you?

**Comment by fippo** [comment]
managed to manually increment the version and publish 4.0.2. we're good now :-)

the 4.0.1 tag looks odd though...

**Pull request merged**
